springdoc:
  api-docs:
    path: /api-docs
spring:
  application:
    name: welcome
  profiles:
    active: dev
# Nivel de log para la aplicación en general
logging:
  level:
    root: INFO
  file:
    name: myapp.log